// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: pkg/types/200/types.proto

package cni

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	CNI_AddAttachment_FullMethodName    = "/cni.CNI/AddAttachment"
	CNI_DeleteAttachment_FullMethodName = "/cni.CNI/DeleteAttachment"
	CNI_RegisterNetwork_FullMethodName  = "/cni.CNI/RegisterNetwork"
	CNI_VerifyAttachment_FullMethodName = "/cni.CNI/VerifyAttachment"
	CNI_AtachmentStatus_FullMethodName  = "/cni.CNI/AtachmentStatus"
	CNI_NetworkStatus_FullMethodName    = "/cni.CNI/NetworkStatus"
	CNI_QueryNetwork_FullMethodName     = "/cni.CNI/QueryNetwork"
)

// CNIClient is the client API for CNI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CNIClient interface {
	// MVP
	AddAttachment(ctx context.Context, in *AddAttachmentRequest, opts ...grpc.CallOption) (*AddAttachmentResponse, error)
	// MVP
	DeleteAttachment(ctx context.Context, in *DeleteAttachmentRequest, opts ...grpc.CallOption) (*DeleteAttachmentResponse, error)
	// MVP
	RegisterNetwork(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*NetworkResponse, error)
	VerifyAttachment(ctx context.Context, in *VerifyAttachmentRequest, opts ...grpc.CallOption) (*VerifyAttachmentResponse, error)
	AtachmentStatus(ctx context.Context, in *AttachmentStatusRequest, opts ...grpc.CallOption) (*AttachmentStatusResponse, error)
	NetworkStatus(ctx context.Context, in *NetworkStatusRequest, opts ...grpc.CallOption) (*NetworkStatusResponse, error)
	QueryNetwork(ctx context.Context, in *QueryNetworkRequest, opts ...grpc.CallOption) (*QueryNetworkResponse, error)
}

type cNIClient struct {
	cc grpc.ClientConnInterface
}

func NewCNIClient(cc grpc.ClientConnInterface) CNIClient {
	return &cNIClient{cc}
}

func (c *cNIClient) AddAttachment(ctx context.Context, in *AddAttachmentRequest, opts ...grpc.CallOption) (*AddAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAttachmentResponse)
	err := c.cc.Invoke(ctx, CNI_AddAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cNIClient) DeleteAttachment(ctx context.Context, in *DeleteAttachmentRequest, opts ...grpc.CallOption) (*DeleteAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAttachmentResponse)
	err := c.cc.Invoke(ctx, CNI_DeleteAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cNIClient) RegisterNetwork(ctx context.Context, in *NetworkRequest, opts ...grpc.CallOption) (*NetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkResponse)
	err := c.cc.Invoke(ctx, CNI_RegisterNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cNIClient) VerifyAttachment(ctx context.Context, in *VerifyAttachmentRequest, opts ...grpc.CallOption) (*VerifyAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyAttachmentResponse)
	err := c.cc.Invoke(ctx, CNI_VerifyAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cNIClient) AtachmentStatus(ctx context.Context, in *AttachmentStatusRequest, opts ...grpc.CallOption) (*AttachmentStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachmentStatusResponse)
	err := c.cc.Invoke(ctx, CNI_AtachmentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cNIClient) NetworkStatus(ctx context.Context, in *NetworkStatusRequest, opts ...grpc.CallOption) (*NetworkStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetworkStatusResponse)
	err := c.cc.Invoke(ctx, CNI_NetworkStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cNIClient) QueryNetwork(ctx context.Context, in *QueryNetworkRequest, opts ...grpc.CallOption) (*QueryNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryNetworkResponse)
	err := c.cc.Invoke(ctx, CNI_QueryNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CNIServer is the server API for CNI service.
// All implementations should embed UnimplementedCNIServer
// for forward compatibility
type CNIServer interface {
	// MVP
	AddAttachment(context.Context, *AddAttachmentRequest) (*AddAttachmentResponse, error)
	// MVP
	DeleteAttachment(context.Context, *DeleteAttachmentRequest) (*DeleteAttachmentResponse, error)
	// MVP
	RegisterNetwork(context.Context, *NetworkRequest) (*NetworkResponse, error)
	VerifyAttachment(context.Context, *VerifyAttachmentRequest) (*VerifyAttachmentResponse, error)
	AtachmentStatus(context.Context, *AttachmentStatusRequest) (*AttachmentStatusResponse, error)
	NetworkStatus(context.Context, *NetworkStatusRequest) (*NetworkStatusResponse, error)
	QueryNetwork(context.Context, *QueryNetworkRequest) (*QueryNetworkResponse, error)
}

// UnimplementedCNIServer should be embedded to have forward compatible implementations.
type UnimplementedCNIServer struct {
}

func (UnimplementedCNIServer) AddAttachment(context.Context, *AddAttachmentRequest) (*AddAttachmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAttachment not implemented")
}
func (UnimplementedCNIServer) DeleteAttachment(context.Context, *DeleteAttachmentRequest) (*DeleteAttachmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAttachment not implemented")
}
func (UnimplementedCNIServer) RegisterNetwork(context.Context, *NetworkRequest) (*NetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterNetwork not implemented")
}
func (UnimplementedCNIServer) VerifyAttachment(context.Context, *VerifyAttachmentRequest) (*VerifyAttachmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyAttachment not implemented")
}
func (UnimplementedCNIServer) AtachmentStatus(context.Context, *AttachmentStatusRequest) (*AttachmentStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AtachmentStatus not implemented")
}
func (UnimplementedCNIServer) NetworkStatus(context.Context, *NetworkStatusRequest) (*NetworkStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetworkStatus not implemented")
}
func (UnimplementedCNIServer) QueryNetwork(context.Context, *QueryNetworkRequest) (*QueryNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryNetwork not implemented")
}

// UnsafeCNIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CNIServer will
// result in compilation errors.
type UnsafeCNIServer interface {
	mustEmbedUnimplementedCNIServer()
}

func RegisterCNIServer(s grpc.ServiceRegistrar, srv CNIServer) {
	s.RegisterService(&CNI_ServiceDesc, srv)
}

func _CNI_AddAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CNIServer).AddAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CNI_AddAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CNIServer).AddAttachment(ctx, req.(*AddAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CNI_DeleteAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CNIServer).DeleteAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CNI_DeleteAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CNIServer).DeleteAttachment(ctx, req.(*DeleteAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CNI_RegisterNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CNIServer).RegisterNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CNI_RegisterNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CNIServer).RegisterNetwork(ctx, req.(*NetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CNI_VerifyAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CNIServer).VerifyAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CNI_VerifyAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CNIServer).VerifyAttachment(ctx, req.(*VerifyAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CNI_AtachmentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachmentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CNIServer).AtachmentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CNI_AtachmentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CNIServer).AtachmentStatus(ctx, req.(*AttachmentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CNI_NetworkStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetworkStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CNIServer).NetworkStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CNI_NetworkStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CNIServer).NetworkStatus(ctx, req.(*NetworkStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CNI_QueryNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CNIServer).QueryNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CNI_QueryNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CNIServer).QueryNetwork(ctx, req.(*QueryNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CNI_ServiceDesc is the grpc.ServiceDesc for CNI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CNI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cni.CNI",
	HandlerType: (*CNIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAttachment",
			Handler:    _CNI_AddAttachment_Handler,
		},
		{
			MethodName: "DeleteAttachment",
			Handler:    _CNI_DeleteAttachment_Handler,
		},
		{
			MethodName: "RegisterNetwork",
			Handler:    _CNI_RegisterNetwork_Handler,
		},
		{
			MethodName: "VerifyAttachment",
			Handler:    _CNI_VerifyAttachment_Handler,
		},
		{
			MethodName: "AtachmentStatus",
			Handler:    _CNI_AtachmentStatus_Handler,
		},
		{
			MethodName: "NetworkStatus",
			Handler:    _CNI_NetworkStatus_Handler,
		},
		{
			MethodName: "QueryNetwork",
			Handler:    _CNI_QueryNetwork_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/types/200/types.proto",
}
